export const TABLE_DATA_REQUEST = 'TABLE_DATA_REQUEST';
export const TABLE_DATA_SUCCESS = 'TABLE_DATA_SUCCESS';
export const TABLE_DATA_FAILURE = 'TABLE_DATA_FAILURE';

export const INPUT_DATA_REQUEST = 'INPUT_DATA_REQUEST';
export const INPUT_DATA_SUCCESS = 'INPUT_DATA_SUCCESS';
export const INPUT_DATA_FAILURE = 'INPUT_DATA_FAILURE';